[preferred]
rg.freedesktop.impl.portal.Secret=gnome-keyring

### My addition ###
# ignore inhibit bc gtk portal always returns as success,
# despite sway/the wlr portal not having an implementation,
# stopping firefox from using wayland idle-inhibit
org.freedesktop.impl.portal.Inhibit=none
